<?php

use Drupal\degov_common\Common;


/**
 * Implements hook_modules_installed().
 */
function degov_media_overrides_modules_installed($modules) {
  // Check if we have a config to be installed for the module.
  if (in_array('degov_media_audio', $modules)) {
    \Drupal::service('degov_config.module_updater')->onModuleInstalled('degov_media_overrides', 'degov_media_audio');
  }
  if (in_array('degov_media_gallery', $modules)) {
    \Drupal::service('degov_config.module_updater')->onModuleInstalled('degov_media_overrides', 'degov_media_gallery');
  }
  if (in_array('degov_media_image', $modules)) {
    \Drupal::service('degov_config.module_updater')->onModuleInstalled('degov_media_overrides', 'degov_media_image');
  }
  if (in_array('degov_media_video', $modules)) {
    \Drupal::service('degov_config.module_updater')->onModuleInstalled('degov_media_overrides', 'degov_media_video');
  }
  if (in_array('degov_media_video_upload', $modules)) {
    \Drupal::service('degov_config.module_updater')->onModuleInstalled('degov_media_overrides', 'degov_media_video_upload');
  }

}

/**
 * Implements hook_preprocess().
 */
function degov_media_overrides_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions for audio.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_overrides',
    'entity_type' => 'media',
    'entity_bundles' => ['audio'],
    'entity_view_modes' => ['full', 'preview_wide']
  ]);
  // Add template suggestions for gallery.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_overrides',
    'entity_type' => 'media',
    'entity_bundles' => ['gallery'],
    'entity_view_modes' => ['full', 'preview_wide']
  ]);
  // Add template suggestions for image.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_overrides',
    'entity_type' => 'media',
    'entity_bundles' => ['image'],
    'entity_view_modes' => ['full', 'preview_wide']
  ]);
  // Add template suggestions for video.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_overrides',
    'entity_type' => 'media',
    'entity_bundles' => ['video'],
    'entity_view_modes' => ['full', 'preview_wide']
  ]);
  // Add template suggestions for video_upload
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_overrides',
    'entity_type' => 'media',
    'entity_bundles' => ['video_upload'],
    'entity_view_modes' => ['full', 'preview_wide']
  ]);
}
