<?php

/**
 * @file
 * Support for file media assets in Lightning.
 */

use Drupal\lightning_core\OverrideHelper;
use Drupal\lightning_media_document\Plugin\media\Source\File;

/**
 * Implements hook_media_source_info_alter().
 */
function lightning_media_document_media_source_info_alter(array &$sources) {
  $sources['file']['input_match']['field_types'] = ['file'];
  OverrideHelper::pluginClass($sources['file'], File::class);
}
