<?php

/**
 * @file
 * Support for videos as media entities in Lightning.
 */

use Drupal\lightning_core\OverrideHelper;
use Drupal\lightning_media_video\Plugin\media\Source\Video;

/**
 * Implements hook_media_source_info_alter().
 */
function lightning_media_video_media_source_info_alter(array &$sources) {
  $sources['video_embed_field']['input_match'] = [
    'field_types' => [
      'string',
      'string_long',
      'video_embed_field',
    ],
  ];
  $sources['video_embed_field']['preview'] = TRUE;

  OverrideHelper::pluginClass($sources['video_embed_field'], Video::class);
}
