; This file was auto-generated by drush make
core = 8.x
api = 2

; Defaults
defaults[projects][subdir] = "contrib"

; Core
projects[drupal][type] = "core"
projects[drupal][download][type] = "git"
projects[drupal][download][url] = "https://github.com/drupal/core.git"
projects[drupal][download][tag] = "8.5.4"
projects[drupal][patch][0] = "https://www.drupal.org/files/issues/1356278-408--8.5.x-real.patch"
projects[drupal][patch][1] = "https://www.drupal.org/files/issues/2880374-remove-experimental-warnings-6.patch"
projects[drupal][patch][2] = "https://www.drupal.org/files/issues/2869592-remove-update-warning-7.patch"
projects[drupal][patch][3] = "https://www.drupal.org/files/issues/2885441-2.patch"
projects[drupal][patch][4] = "https://www.drupal.org/files/issues/2018-06-07/2815221-102.patch"
projects[drupal][patch][5] = "https://www.drupal.org/files/issues/2877383-56.patch"
projects[drupal][patch][6] = "https://www.drupal.org/files/issues/2670730-81-89-8.5.0-rc1.patch"

; Modules
projects[acquia_connector][type] = "module"
projects[acquia_connector][download][type] = "git"
projects[acquia_connector][download][url] = "https://git.drupal.org/project/acquia_connector"
projects[acquia_connector][download][tag] = "1.x-14.0"

projects[address][type] = "module"
projects[address][download][type] = "git"
projects[address][download][url] = "https://git.drupal.org/project/address"
projects[address][download][tag] = "1.x-4.0"

projects[admin_links_access_filter][type] = "module"
projects[admin_links_access_filter][download][type] = "git"
projects[admin_links_access_filter][download][url] = "https://git.drupal.org/project/admin_links_access_filter"
projects[admin_links_access_filter][download][tag] = "1.x-0.0-alpha3"

projects[admin_toolbar][type] = "module"
projects[admin_toolbar][download][type] = "git"
projects[admin_toolbar][download][url] = "https://git.drupal.org/project/admin_toolbar"
projects[admin_toolbar][download][tag] = "1.x-24.0"

projects[block_field][type] = "module"
projects[block_field][download][type] = "git"
projects[block_field][download][url] = "https://git.drupal.org/project/block_field"
projects[block_field][download][tag] = "1.x-0.0-alpha6"

projects[calendar][type] = "module"
projects[calendar][download][type] = "git"
projects[calendar][download][url] = "https://git.drupal.org/project/calendar"
projects[calendar][download][branch] = "1.x"
projects[calendar][download][revision] = "73e2979f3ed951b1fb3ad942e2d89d673aa52e1d"
projects[calendar][patch][0] = "https://www.drupal.org/files/issues/undefined_index-2845257-10.patch"

projects[config_rewrite][type] = "module"
projects[config_rewrite][download][type] = "git"
projects[config_rewrite][download][url] = "https://git.drupal.org/project/config_rewrite"
projects[config_rewrite][download][tag] = "1.x-1.0"

projects[config_update][type] = "module"
projects[config_update][download][type] = "git"
projects[config_update][download][url] = "https://git.drupal.org/project/config_update"
projects[config_update][download][tag] = "1.x-5.0"

projects[consumers][type] = "module"
projects[consumers][download][type] = "git"
projects[consumers][download][url] = "https://git.drupal.org/project/consumers"
projects[consumers][download][tag] = "1.x-0.0-beta3"

projects[contact_storage][type] = "module"
projects[contact_storage][download][type] = "git"
projects[contact_storage][download][url] = "https://git.drupal.org/project/contact_storage"
projects[contact_storage][download][tag] = "1.x-0.0-beta9"

projects[crop][type] = "module"
projects[crop][download][type] = "git"
projects[crop][download][url] = "https://git.drupal.org/project/crop"
projects[crop][download][tag] = "2.x-0.0-rc1"

projects[ctools][type] = "module"
projects[ctools][download][type] = "git"
projects[ctools][download][url] = "https://git.drupal.org/project/ctools"
projects[ctools][download][tag] = "3.x-0.0"

projects[date_popup][type] = "module"
projects[date_popup][download][type] = "git"
projects[date_popup][download][url] = "https://git.drupal.org/project/date_popup"
projects[date_popup][download][tag] = "1.x-0.0"

projects[diff][type] = "module"
projects[diff][download][type] = "git"
projects[diff][download][url] = "https://git.drupal.org/project/diff"
projects[diff][download][tag] = "1.x-0.0-rc1"

projects[dropzonejs][type] = "module"
projects[dropzonejs][download][type] = "git"
projects[dropzonejs][download][url] = "https://git.drupal.org/project/dropzonejs"
projects[dropzonejs][download][tag] = "2.x-0.0-alpha3"

projects[easy_breadcrumb][type] = "module"
projects[easy_breadcrumb][download][type] = "git"
projects[easy_breadcrumb][download][url] = "https://git.drupal.org/project/easy_breadcrumb"
projects[easy_breadcrumb][download][tag] = "1.x-8.0"

projects[embed][type] = "module"
projects[embed][download][type] = "git"
projects[embed][download][url] = "https://git.drupal.org/project/embed"
projects[embed][download][tag] = "1.x-0.0"

projects[entity_block][type] = "module"
projects[entity_block][download][type] = "git"
projects[entity_block][download][url] = "https://git.drupal.org/project/entity_block"
projects[entity_block][download][tag] = "1.x-0.0-beta1"

projects[entity_browser][type] = "module"
projects[entity_browser][download][type] = "git"
projects[entity_browser][download][url] = "https://git.drupal.org/project/entity_browser"
projects[entity_browser][download][tag] = "2.x-0.0-alpha2"
projects[entity_browser][patch][0] = "https://www.drupal.org/files/issues/entity-browser-view-context-2865928-14.patch"
projects[entity_browser][patch][1] = "https://www.drupal.org/files/issues/2877751-27-8.x-2.x.patch"

projects[entity_embed][type] = "module"
projects[entity_embed][download][type] = "git"
projects[entity_embed][download][url] = "https://git.drupal.org/project/entity_embed"
projects[entity_embed][download][tag] = "1.x-0.0-beta2"
projects[entity_embed][patch][0] = "https://www.drupal.org/files/issues/2832504-2.patch"

projects[entity_reference_display][type] = "module"
projects[entity_reference_display][download][type] = "git"
projects[entity_reference_display][download][url] = "https://git.drupal.org/project/entity_reference_display"
projects[entity_reference_display][download][tag] = "1.x-2.0"

projects[entity_reference_integrity][type] = "module"
projects[entity_reference_integrity][download][type] = "git"
projects[entity_reference_integrity][download][url] = "https://git.drupal.org/project/entity_reference_integrity"
projects[entity_reference_integrity][download][tag] = "1.x-0.0-rc4"

projects[entity_reference_revisions][type] = "module"
projects[entity_reference_revisions][download][type] = "git"
projects[entity_reference_revisions][download][url] = "https://git.drupal.org/project/entity_reference_revisions"
projects[entity_reference_revisions][download][tag] = "1.x-5.0"

projects[eu_cookie_compliance][type] = "module"
projects[eu_cookie_compliance][download][type] = "git"
projects[eu_cookie_compliance][download][url] = "https://git.drupal.org/project/eu-cookie-compliance"
projects[eu_cookie_compliance][download][tag] = "1.x-0.0"

projects[facets][type] = "module"
projects[facets][download][type] = "git"
projects[facets][download][url] = "https://git.drupal.org/project/facets"
projects[facets][download][tag] = "1.x-0.0-beta2"

projects[features][type] = "module"
projects[features][download][type] = "git"
projects[features][download][url] = "https://git.drupal.org/project/features"
projects[features][download][tag] = "3.x-7.0"

projects[field_group][type] = "module"
projects[field_group][download][type] = "git"
projects[field_group][download][url] = "https://git.drupal.org/project/field_group"
projects[field_group][download][branch] = "3.x"
projects[field_group][download][revision] = "9ab1b9963a07bdefde4829b025a1ea56cb63e03e"

projects[geocoder][type] = "module"
projects[geocoder][download][type] = "git"
projects[geocoder][download][url] = "https://git.drupal.org/project/geocoder"
projects[geocoder][download][tag] = "2.x-0.0-beta3"

projects[geofield][type] = "module"
projects[geofield][download][type] = "git"
projects[geofield][download][url] = "https://git.drupal.org/project/geofield"
projects[geofield][download][tag] = "1.x-0.0-beta4"

projects[image_widget_crop][type] = "module"
projects[image_widget_crop][download][type] = "git"
projects[image_widget_crop][download][url] = "https://git.drupal.org/project/image_widget_crop"
projects[image_widget_crop][download][tag] = "2.x-1.0"

projects[imagick][type] = "module"
projects[imagick][download][type] = "git"
projects[imagick][download][url] = "https://git.drupal.org/project/imagick"
projects[imagick][download][tag] = "1.x-1.0"

projects[inline_entity_form][type] = "module"
projects[inline_entity_form][download][type] = "git"
projects[inline_entity_form][download][url] = "https://git.drupal.org/project/inline_entity_form"
projects[inline_entity_form][download][tag] = "1.x-0.0-rc1"

projects[jsonapi][type] = "module"
projects[jsonapi][download][type] = "git"
projects[jsonapi][download][url] = "https://git.drupal.org/project/jsonapi"
projects[jsonapi][download][tag] = "1.x-16.0"

projects[lightning_api][type] = "module"
projects[lightning_api][download][type] = "git"
projects[lightning_api][download][url] = "https://git.drupal.org/project/lightning_api"
projects[lightning_api][download][tag] = "2.x-3.0"

projects[lightning_core][type] = "module"
projects[lightning_core][download][type] = "git"
projects[lightning_core][download][url] = "https://git.drupal.org/project/lightning_core"
projects[lightning_core][download][tag] = "2.x-7.0"

projects[lightning_layout][type] = "module"
projects[lightning_layout][download][type] = "git"
projects[lightning_layout][download][url] = "https://git.drupal.org/project/lightning_layout"
projects[lightning_layout][download][tag] = "1.x-2.0"

projects[lightning_media][type] = "module"
projects[lightning_media][download][type] = "git"
projects[lightning_media][download][url] = "https://git.drupal.org/project/lightning_media"
projects[lightning_media][download][tag] = "2.x-3.0"

projects[lightning_workflow][type] = "module"
projects[lightning_workflow][download][type] = "git"
projects[lightning_workflow][download][url] = "https://git.drupal.org/project/lightning_workflow"
projects[lightning_workflow][download][tag] = "1.x-2.0"

projects[linkit][type] = "module"
projects[linkit][download][type] = "git"
projects[linkit][download][url] = "https://git.drupal.org/project/linkit"
projects[linkit][download][tag] = "4.x-3.0"

projects[mailsystem][type] = "module"
projects[mailsystem][download][type] = "git"
projects[mailsystem][download][url] = "https://git.drupal.org/project/mailsystem"
projects[mailsystem][download][tag] = "4.x-1.0"

projects[matomo][type] = "module"
projects[matomo][download][type] = "git"
projects[matomo][download][url] = "https://git.drupal.org/project/matomo"
projects[matomo][download][tag] = "1.x-5.0"

projects[media_entity_generic][type] = "module"
projects[media_entity_generic][download][type] = "git"
projects[media_entity_generic][download][url] = "https://git.drupal.org/project/media_entity_generic"
projects[media_entity_generic][download][tag] = "1.x-0.0-alpha1"

projects[media_entity_instagram][type] = "module"
projects[media_entity_instagram][download][type] = "git"
projects[media_entity_instagram][download][url] = "https://git.drupal.org/project/media_entity_instagram"
projects[media_entity_instagram][download][tag] = "2.x-0.0-alpha1"
projects[media_entity_instagram][patch][0] = "https://www.drupal.org/files/issues/2917454-2.patch"

projects[media_entity_twitter][type] = "module"
projects[media_entity_twitter][download][type] = "git"
projects[media_entity_twitter][download][url] = "https://git.drupal.org/project/media_entity_twitter"
projects[media_entity_twitter][download][tag] = "2.x-0.0-alpha2"

projects[memcache_storage][type] = "module"
projects[memcache_storage][download][type] = "git"
projects[memcache_storage][download][url] = "https://git.drupal.org/project/memcache_storage"
projects[memcache_storage][download][tag] = "1.x-0.0-beta2"

projects[metatag][type] = "module"
projects[metatag][download][type] = "git"
projects[metatag][download][url] = "https://git.drupal.org/project/metatag"
projects[metatag][download][tag] = "1.x-5.0"

projects[open_readspeaker][type] = "module"
projects[open_readspeaker][download][type] = "git"
projects[open_readspeaker][download][url] = "https://git.drupal.org/project/open_readspeaker"
projects[open_readspeaker][download][tag] = "1.x-4.0"

projects[openapi][type] = "module"
projects[openapi][download][type] = "git"
projects[openapi][download][url] = "https://git.drupal.org/project/openapi"
projects[openapi][download][tag] = "1.x-0.0-alpha1"

projects[panelizer][type] = "module"
projects[panelizer][download][type] = "git"
projects[panelizer][download][url] = "https://git.drupal.org/project/panelizer"
projects[panelizer][download][tag] = "4.x-1.0"

projects[panels][type] = "module"
projects[panels][download][type] = "git"
projects[panels][download][url] = "https://git.drupal.org/project/panels"
projects[panels][download][tag] = "4.x-3.0"
projects[panels][patch][0] = "https://www.drupal.org/files/issues/panels-ipe-2878684-3.patch"
projects[panels][patch][1] = "https://www.drupal.org/files/issues/panels-ipe-propogate-errors-2825034-5.patch"

projects[paragraphs][type] = "module"
projects[paragraphs][download][type] = "git"
projects[paragraphs][download][url] = "https://git.drupal.org/project/paragraphs"
projects[paragraphs][download][tag] = "1.x-3.0"

projects[paragraphs_edit][type] = "module"
projects[paragraphs_edit][download][type] = "git"
projects[paragraphs_edit][download][url] = "https://git.drupal.org/project/paragraphs_edit"
projects[paragraphs_edit][download][branch] = "2.x"
projects[paragraphs_edit][download][revision] = "1551330f27db8704aac59a5c8b397d7c425c5cc6"

projects[password_policy][type] = "module"
projects[password_policy][download][type] = "git"
projects[password_policy][download][url] = "https://git.drupal.org/project/password_policy"
projects[password_policy][download][tag] = "3.x-0.0-alpha4"

projects[pathauto][type] = "module"
projects[pathauto][download][type] = "git"
projects[pathauto][download][url] = "https://git.drupal.org/project/pathauto"
projects[pathauto][download][tag] = "1.x-2.0"

projects[piwik][type] = "module"
projects[piwik][download][type] = "git"
projects[piwik][download][url] = "https://git.drupal.org/project/piwik"
projects[piwik][download][tag] = "1.x-4.0"

projects[redirect][type] = "module"
projects[redirect][download][type] = "git"
projects[redirect][download][url] = "https://git.drupal.org/project/redirect"
projects[redirect][download][tag] = "1.x-2.0"

projects[restrict_ip][type] = "module"
projects[restrict_ip][download][type] = "git"
projects[restrict_ip][download][url] = "https://git.drupal.org/project/restrict_ip"
projects[restrict_ip][download][tag] = "1.x-3.0"
projects[restrict_ip][patch][0] = "https://www.drupal.org/files/issues/2905569_check_user_authentication.patch"

projects[role_delegation][type] = "module"
projects[role_delegation][download][type] = "git"
projects[role_delegation][download][url] = "https://git.drupal.org/project/role_delegation"
projects[role_delegation][download][tag] = "1.x-0.0-alpha1"

projects[scheduled_updates][type] = "module"
projects[scheduled_updates][download][type] = "git"
projects[scheduled_updates][download][url] = "https://git.drupal.org/project/scheduled_updates"
projects[scheduled_updates][download][tag] = "1.x-0.0-alpha7"

projects[schemata][type] = "module"
projects[schemata][download][type] = "git"
projects[schemata][download][url] = "https://git.drupal.org/project/schemata"
projects[schemata][download][tag] = "1.x-0.0-alpha3"

projects[search_api][type] = "module"
projects[search_api][download][type] = "git"
projects[search_api][download][url] = "https://git.drupal.org/project/search_api"
projects[search_api][download][tag] = "1.x-8.0"

projects[search_api_solr][type] = "module"
projects[search_api_solr][download][type] = "git"
projects[search_api_solr][download][url] = "https://git.drupal.org/project/search_api_solr"
projects[search_api_solr][download][tag] = "1.x-2.0"

projects[search_api_sorts][type] = "module"
projects[search_api_sorts][download][type] = "git"
projects[search_api_sorts][download][url] = "https://git.drupal.org/project/search_api_sorts"
projects[search_api_sorts][download][tag] = "1.x-0.0-beta1"

projects[shariff][type] = "module"
projects[shariff][download][type] = "git"
projects[shariff][download][url] = "https://git.drupal.org/project/shariff"
projects[shariff][download][tag] = "1.x-3.0"

projects[simple_oauth][type] = "module"
projects[simple_oauth][download][type] = "git"
projects[simple_oauth][download][url] = "https://git.drupal.org/project/simple_oauth"
projects[simple_oauth][download][tag] = "3.x-6.0"
projects[simple_oauth][patch][0] = "https://www.drupal.org/files/issues/2018-04-27/2966590-3.patch"

projects[simple_sitemap][type] = "module"
projects[simple_sitemap][download][type] = "git"
projects[simple_sitemap][download][url] = "https://git.drupal.org/project/simple_sitemap"
projects[simple_sitemap][download][tag] = "2.x-12.0"

projects[simplenews][type] = "module"
projects[simplenews][download][type] = "git"
projects[simplenews][download][url] = "https://git.drupal.org/project/simplenews"
projects[simplenews][download][tag] = "1.x-0.0-alpha3"

projects[sitemap][type] = "module"
projects[sitemap][download][type] = "git"
projects[sitemap][download][url] = "https://git.drupal.org/project/sitemap"
projects[sitemap][download][tag] = "1.x-4.0"

projects[spamspan][type] = "module"
projects[spamspan][download][type] = "git"
projects[spamspan][download][url] = "https://git.drupal.org/project/spamspan"
projects[spamspan][download][branch] = "1.x"
projects[spamspan][download][revision] = "f2746f00cbfebbe49848a8a503a8d41a97e29901"

projects[styled_google_map][type] = "module"
projects[styled_google_map][download][type] = "git"
projects[styled_google_map][download][url] = "https://git.drupal.org/project/styled_google_map"
projects[styled_google_map][download][tag] = "1.x-2.0"

projects[swiftmailer][type] = "module"
projects[swiftmailer][download][type] = "git"
projects[swiftmailer][download][url] = "https://git.drupal.org/project/swiftmailer"
projects[swiftmailer][download][tag] = "1.x-0.0-beta2"

projects[system_stream_wrapper][type] = "module"
projects[system_stream_wrapper][download][type] = "git"
projects[system_stream_wrapper][download][url] = "https://git.drupal.org/project/system_stream_wrapper"
projects[system_stream_wrapper][download][tag] = "1.x-0.0-alpha2"

projects[token][type] = "module"
projects[token][download][type] = "git"
projects[token][download][url] = "https://git.drupal.org/project/token"
projects[token][download][tag] = "1.x-3.0"

projects[twig_field_value][type] = "module"
projects[twig_field_value][download][type] = "git"
projects[twig_field_value][download][url] = "https://git.drupal.org/project/twig_field_value"
projects[twig_field_value][download][tag] = "1.x-1.0"

projects[ultimate_cron][type] = "module"
projects[ultimate_cron][download][type] = "git"
projects[ultimate_cron][download][url] = "https://git.drupal.org/project/ultimate_cron"
projects[ultimate_cron][download][tag] = "2.x-0.0-alpha4"

projects[video_embed_field][type] = "module"
projects[video_embed_field][download][type] = "git"
projects[video_embed_field][download][url] = "https://git.drupal.org/project/video_embed_field"
projects[video_embed_field][download][tag] = "2.x-0.0"

projects[views_infinite_scroll][type] = "module"
projects[views_infinite_scroll][download][type] = "git"
projects[views_infinite_scroll][download][url] = "https://git.drupal.org/project/views_infinite_scroll"
projects[views_infinite_scroll][download][tag] = "1.x-5.0"

projects[views_templates][type] = "module"
projects[views_templates][download][type] = "git"
projects[views_templates][download][url] = "https://git.drupal.org/project/views_templates"
projects[views_templates][download][tag] = "1.x-0.0-alpha1"

projects[viewsreference][type] = "module"
projects[viewsreference][download][type] = "git"
projects[viewsreference][download][url] = "https://git.drupal.org/project/viewsreference"
projects[viewsreference][download][tag] = "1.x-2.0"

projects[webform][type] = "module"
projects[webform][download][type] = "git"
projects[webform][download][url] = "https://git.drupal.org/project/webform"
projects[webform][download][tag] = "5.x-0.0-rc15"

projects[workbench][type] = "module"
projects[workbench][download][type] = "git"
projects[workbench][download][url] = "https://git.drupal.org/project/workbench"
projects[workbench][download][tag] = "1.x-0.0"

projects[workbench_access][type] = "module"
projects[workbench_access][download][type] = "git"
projects[workbench_access][download][url] = "https://git.drupal.org/project/workbench_access"
projects[workbench_access][download][tag] = "1.x-0.0-alpha6"

projects[workbench_moderation][type] = "module"
projects[workbench_moderation][download][type] = "git"
projects[workbench_moderation][download][url] = "https://git.drupal.org/project/workbench_moderation"
projects[workbench_moderation][download][tag] = "1.x-3.0"

; Themes
projects[bootstrap][type] = "theme"
projects[bootstrap][download][type] = "git"
projects[bootstrap][download][url] = "https://git.drupal.org/project/bootstrap"
projects[bootstrap][download][tag] = "3.x-11.0"

; Libraries
libraries[degov/degov][type] = "library"
libraries[degov/degov][download][type] = "git"
libraries[degov/degov][download][url] = "https://bitbucket.org/publicplan/degov.git"
libraries[degov/degov][download][branch] = "dev-feature/add-social-media-sliders"
libraries[degov/degov][download][revision] = "d659e0e3aa4cb9389175d8ee5620c64b8595dd74"

libraries[madcoda/php-youtube-api][type] = "library"
libraries[madcoda/php-youtube-api][download][type] = "git"
libraries[madcoda/php-youtube-api][download][url] = "https://github.com/madcoda/php-youtube-api.git"
libraries[madcoda/php-youtube-api][download][branch] = "v1.2.4"
libraries[madcoda/php-youtube-api][download][revision] = "886e3aa1789cd19ad0c7add239bd2967f3b5ad4d"

libraries[raiym/instagram-php-scraper][type] = "library"
libraries[raiym/instagram-php-scraper][download][type] = "git"
libraries[raiym/instagram-php-scraper][download][url] = "https://github.com/postaddictme/instagram-php-scraper.git"
libraries[raiym/instagram-php-scraper][download][branch] = "v0.8.22"
libraries[raiym/instagram-php-scraper][download][revision] = "c36ca08724fb20e0c03e473f7398aefea87cf359"


