<?php

/**
 * @file
 * The deGov Media file links module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_locale_translation_projects_alter().
 */
function media_file_links_locale_translation_projects_alter(&$projects) {
  $projects['media_file_links'] = [
    'info' => [
      'name'                                 => 'Media file links',
      'interface translation project'        => 'media_file_links',
      'interface translation server pattern' => drupal_get_path('module', 'media_file_links') . '/translations/%language.po',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function media_file_links_form_linkit_editor_dialog_form_alter(&$form, FormStateInterface $form_state) {
  $form['#attached']['library'][] = 'media_file_links/fontawesome';
}