<?php

namespace Drupal\degov_demo_content\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\degov_demo_content\Service\ContentGenerator;

/**
 * Class ContentGeneratorForm.
 */
class ContentGeneratorForm extends FormBase {

  /**
   * Drupal\degov_demo_content\Service\ContentGenerator definition.
   *
   * @var \Drupal\degov_demo_content\Service\ContentGenerator
   */
  protected $degovDemoContentContentGenerator;

  /**
   * Constructs a new ContentGeneratorForm object.
   */
  public function __construct(
    ContentGenerator $degov_demo_content_content_generator
  ) {
    $this->degovDemoContentContentGenerator = $degov_demo_content_content_generator;
  }

  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('degov_demo_content.content_generator')
    );
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'content_generator_form';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $form['submit_description'] = [
      '#markup' => sprintf('<p>%s</p>', $this->t('All entities generated by this module will be deleted and generated anew. Any changes you made to these entities will be lost.')),
    ];
    $form['submit_reset'] = [
      '#type'  => 'submit',
      '#value' => $this->t('Reset demo content'),
    ];

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    parent::validateForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $this->degovDemoContentContentGenerator->resetMedia();
  }

}
