<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\degov_search_media_manager\FormAlter;
use Drupal\media\MediaInterface;

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function degov_search_media_manager_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(FormAlter::class)
    ->formAlter($form, $form_state, $form_id);
}
