<?php

use Drupal\degov_common\Common;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_preprocess().
 */
function degov_media_image_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name'       => 'degov_media_image',
    'entity_type'       => 'media',
    'entity_bundles'    => ['image'],
    'entity_view_modes' => [
      'thumbnail',
      'usage',
      'preview',
      'search',
      'embedded',
      'full',
      'preview_wide',
    ],
  ]);
}

/**
 * Implements hook_preprocess_type().
 */
function degov_media_image_preprocess_media__image(&$variables) {
  /** @var Drupal\media\Entity\Media $media */
  $media = $variables['elements']['#media'];
  $variables['created'] = $media->created->value;
  $variables['image_url'] = $media->url();

  // Add the download link only to full view mode.
  if (in_array($variables['elements']['#view_mode'], ['full', 'default'])) {
    // Add media type name to display.
    if (isset($variables['content']['media_type_label'])) {
      $bundle_definition = $media->getSource()->getPluginDefinition();
      $variables['content']['media_type_label'] = $bundle_definition['label'];
    }
    // Check if the download of the video is allowed by media settings.
    $download_is_allowed = FALSE;
    if ($media->hasField('field_allow_download') && !$media->get('field_allow_download')
        ->isEmpty()) {
      $download_is_allowed = $media->get('field_allow_download')->value ? TRUE : FALSE;
    }
    // If allowed let's prepare the links.
    if ($download_is_allowed) {
      // First check if the image is there.
      if (!$media->get('image')->isEmpty()) {
        /** @var \Drupal\file\FileInterface $sourceFile */
        $sourceFile = $media->get('image')->entity;
        $variables['content']['download'] = degov_common_file_download_render_array($sourceFile);
      }
      else {
        $variables['content']['download'] = [];
      }
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function degov_media_image_form_media_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  if (in_array($form_id, ['media_image_add_form', 'media_image_edit_form'])) {
    $form['#attached']['library'][] = 'degov_media_image/entity-form';
    $form['#validate'][] = 'degov_media_image_validate';
  }
}

/**
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function degov_media_image_validate(array &$form, FormStateInterface $form_state) {
  $is_royalty_free_image_value = $form_state->getValue('field_royalty_free');
  $is_royalty_free_image = (bool) $is_royalty_free_image_value['value'];
  $field_copyright_value = $form_state->getValue('field_copyright');
  if (!$is_royalty_free_image && empty($field_copyright_value[0]['target_id'])) {
    $form_state->setError($form['field_copyright']['widget'][0]['target_id'], t('@name field is required.', ['@name' => $form['field_copyright']['widget'][0]['target_id']['#title']]));
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function degov_media_image_media_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() === 'image') {
    if ((bool) $entity->field_royalty_free->value === TRUE) {
      unset($build['field_copyright']);
    }
  }
}
