<?php

/**
 * @file
 * Contains degov_demo_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function degov_demo_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the degov_demo_content module.
    case 'help.page.degov_demo_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generates a predefined set of media and node entities for a quick demo setup') . '</p>';
      return $output;

    default:
  }
}
