<?php

/**
 * @file
 * Install, update and uninstall hooks for the degov_taxonomy_term_section module.
 */

use Drupal\degov_common\Common;

/**
 * Implements hook_uninstall().
 */
function degov_taxonomy_term_section_uninstall() {
  // Removes all module type defined content when uninstalling the module.
  Common::removeContent([
    'entity_type' => 'taxonomy_term',
    'entity_bundles' => ['section'],
  ]);
}
