<?php

/**
 * @file
 * Drupal hooks implementations for the degov_content_types_shared_fields module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function degov_content_types_shared_fields_preprocess_node(array &$variables) {
  // Include the shariff sharing block buttons if social media sharing is
  // enabled on the node. Appears on the bottom of both header/content paragraph.
  // Default is 2-click-sharing. Admins can enable 1-click-sharing in settings.

  /* @var \Drupal\node\NodeInterface $node */
  $node = $variables['elements']['#node'];
  $shariff_settings = \Drupal::config('shariff.settings');

  if ($node->hasField('field_social_media')
    && $node->field_social_media->value == '1'
    && !empty($variables['content']['shariff_field']) && !$shariff_settings->get('enable_1_click_sharing')) {
    $variables['content']['shariff_field']['#attached']['library'] = ['degov_content_types_shared_fields/shariff-2click'];
  }
}

/**
 * Implements hook_form_alter().
 */
function degov_content_types_shared_fields_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  if ($form_id === 'shariff_settings_form') {
    $shariff_settings = \Drupal::config('shariff.settings');
    $form['enable_1_click_sharing'] = [
      '#type' => 'checkbox',
      '#title' => t('Enable 1-click sharing'),
      '#description' => t('Enable if users should be able to share content with one click (instead of clicking twice to give their consent).'),
      '#default_value' => $shariff_settings->get('enable_1_click_sharing'),
    ];
  }
}
