<?php

/**
 * @file
 * Module file for deGov - Automatic cropping.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\degov_auto_crop\Form\CropOffsetForm;

/**
 * Implements hook_entity_insert().
 */
function degov_auto_crop_entity_insert(EntityInterface $entity) {
  if ($entity->bundle() === 'file') {
    if (preg_match("/^image\//", $entity->getMimeType())) {
      \Drupal::service('degov_auto_crop.auto_cropper')
        ->applyImageCrops($entity);
    }
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function degov_auto_crop_entity_type_alter(array &$entity_types) {
  $entity_types['crop_type']->setHandlerClass('form', [
    'add'  => CropOffsetForm::class,
    'edit' => CropOffsetForm::class,
  ]);
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function degov_auto_crop_locale_translation_projects_alter(&$projects) {
  // Define translation pattern to allow Drupal autodected the .po file.
  $projects['degov_auto_crop'] = [
    'info' => [
      'name'                                  => 'deGov - Automatic cropping',
      'interface translation project'         => 'degov_auto_crop',
      'interface translation server pattern'  => drupal_get_path('module', 'degov_auto_crop').'/translations/%language.po',
    ],
  ];
}
