<?php

use Drupal\node\Entity\Node;

function degov_media_usage_node_node_insert(Node $entity) {
  static $handled = [];

  /** @var \Drupal\degov_media_usage_node\Service\NodePersistance $persistance */
  $persistance = \Drupal::service('degov_media_usage_node.persistance');
  if ($persistance->canHandle($entity) && !in_array($entity->id(), $handled, TRUE)) {
    $media = $persistance->getMedia($entity);
    if (!$media) {
      return false;
    }

    $persistance->store($entity, $media);
    $handled[] = $entity->id();

    return true;
  }

  return false;
}

function degov_media_usage_node_node_update(Node $entity) {
  static $handled = [];

  /** @var \Drupal\degov_media_usage_node\Service\NodePersistance $persistance */
  $persistance = \Drupal::service('degov_media_usage_node.persistance');
  $id = $entity->id();

  if ($persistance->canHandle($entity) && !in_array($id, $handled, TRUE)) {
    $persistance->purge($entity);
    $media = $persistance->getMedia($entity);
    if (!$media) {
      return false;
    }

    $persistance->store($entity, $media);
    $handled[] = $id;

    return true;
  }

  return false;
}

function degov_media_usage_node_node_delete(Node $entity) {
  static $handled = [];

  /** @var \Drupal\degov_media_usage_node\Service\NodePersistance $persistance */
  $persistance = \Drupal::service('degov_media_usage_node.persistance');
  $id = $entity->id();

  if ($persistance->canHandle($entity) && !in_array($id, $handled, TRUE)) {
    $persistance->purge($entity);
    $handled[] = $id;

    return true;
  }

  return false;
}
