<?php

/**
 * @file
 * The deGov Media module.
 */

use Drupal\file\Entity\File;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_delete().
 */
function degov_media_entity_delete(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'media') {
    // Get field definitions for entity type / bundle.
    $bundleFields = \Drupal::service('entity_field.manager')
      ->getFieldDefinitions($entity->getEntityTypeId(), $entity->bundle());
    foreach ($bundleFields as $fieldKey => $field) {
      // Filter out the file fields.
      if (in_array($field->getType(), ['file', 'image'])) {
        // Delete the files associated with the fields.
        $fieldValue = $entity->get($fieldKey)->getValue();
        if (!empty($fieldValue[0]['target_id'])) {
          $referencedFile = File::load($fieldValue[0]['target_id']);
          if ($referencedFile instanceof File) {
            $referencedFile->delete();
          }
        }
      }
    }
  }
}
