<?php

/**
 * Implements hook_locale_translation_projects_alter().
 */
function degov_email_login_locale_translation_projects_alter(&$projects) {
  $projects['degov_email_login'] = [
    'info' => [
      'name'                                 => 'deGov - Email Login',
      'interface translation project'        => 'degov_email_login',
      'interface translation server pattern' => drupal_get_path('module', 'degov_email_login') . '/translations/%language.po',
    ],
  ];
}
