<?php

use Drupal\Component\Utility\Html;
use Drupal\degov_common\Common;
use Drupal\degov_paragraph_slideshow\PreprocessParagraph;


/**
 * Implements hook_preprocess().
 */
function degov_paragraph_slideshow_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_paragraph_slideshow',
    'entity_type' => 'paragraph',
    'entity_bundles' => ['slide', 'slideshow'],
    'entity_view_modes' => ['preview'],
  ]);
}

/**
 * Implements hook_preprocess_paragraph().
 */
function degov_paragraph_slideshow_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  // Add variables to the slideshow template file.
  if ($paragraph->bundle() == 'slideshow') {
    \Drupal::classResolver(PreprocessParagraph::class)
      ->slider($variables);
  }

  // Add variables to the slideshow template file.
  if ($paragraph->bundle() == 'slide') {
    \Drupal::classResolver(PreprocessParagraph::class)
      ->slide($variables);
  }
}

/**
 * Implements hook_preprocess_video_embed_iframe__youtube().
 */
function degov_paragraph_slideshow_preprocess_video_embed_iframe__youtube(&$variables) {
  $variables['query']['enablejsapi'] = 1;
  $variables['#attached']['library'][] = 'degov_paragraph_slideshow/youtube';
}

/**
 * Implements hook_preprocess_video_embed_iframe__vimeo().
 */
function degov_paragraph_slideshow_preprocess_video_embed_iframe__vimeo(&$variables) {
  $variables['#attached']['library'][] = 'degov_paragraph_slideshow/vimeo';
}
