<?php

/**
 * @file
 * Install, update and uninstall hooks for the degov_paragraph_iframe module.
 */

use Drupal\degov_common\Common;

/**
 * Implements hook_uninstall().
 */
function degov_paragraph_iframe_uninstall() {
  // Removes all module type defined content when uninstalling the module.
  Common::removeContent([
    'entity_type' => 'paragraph',
    'entity_bundles' => ['iframe'],
  ]);
}
