<?php

/**
 * @file
 * Install, update and uninstall hooks for the degov_paragraph_header module.
 */

use Drupal\field\Entity\FieldConfig;

/**
 * Remove the unused rich text field field_header_text
 */
function degov_paragraph_header_update_8001() {
  $field_header_text_field_config = FieldConfig::loadByName(
    'paragraph',
    'image_header',
    'field_header_text'
  );
  if ($field_header_text_field_config) {
    $field_header_text_field_config->delete();
  }
}
